@echo off
cd /d %~dp0
manim -ql scene_s03_scatter.py               Scene_s03_scatter
manim -ql scene_s05_simple_vs_multiple.py    Scene_s05_simple_vs_multiple
manim -ql scene_s08_symbol_table.py          Scene_s08_symbol_table
manim -ql scene_s11_coeff_interp.py          Scene_s11_coeff_interp
manim -ql scene_s12_ols_cost.py              Scene_s12_ols_cost
manim -ql scene_s14_normal_eq.py             Scene_s14_normal_eq
manim -ql scene_s15_normal_eq_pc.py          Scene_s15_normal_eq_pc
manim -ql scene_s16_linemo_overview.py       Scene_s16_linemo_overview
manim -ql scene_s18_linearity_pc.py          Scene_s18_linearity_pc
manim -ql scene_s20_homo_pc.py               Scene_s20_homo_pc
manim -ql scene_s22_multi_pc.py              Scene_s22_multi_pc
manim -ql scene_s23_independence.py          Scene_s23_independence
manim -ql scene_s24_independence_pc.py       Scene_s24_independence_pc
manim -ql scene_s26_normality_pc.py          Scene_s26_normality_pc
manim -ql scene_s27_outliers.py              Scene_s27_outliers
manim -ql scene_s29_metrics_overview.py      Scene_s29_metrics_overview
manim -ql scene_s36_r2.py                    Scene_s36_r2
manim -ql scene_s38_r2_pc.py                 Scene_s38_r2_pc
manim -ql scene_s39_adj_r2.py                Scene_s39_adj_r2
manim -ql scene_s40_adj_r2_pc.py             Scene_s40_adj_r2_pc
manim -ql scene_s41_mape.py                  Scene_s41_mape
manim -ql scene_s42_mape_pc.py               Scene_s42_mape_pc
manim -ql scene_s45_gd_steps.py              Scene_s45_gd_steps
manim -ql scene_s46_learning_rate.py         Scene_s46_learning_rate
manim -ql scene_s47_gd_types.py              Scene_s47_gd_types
manim -ql scene_s48_gd_pc.py                 Scene_s48_gd_pc
manim -ql scene_s50_ridge.py                 Scene_s50_ridge
manim -ql scene_s53_lasso_geometry.py        Scene_s53_lasso_geometry
manim -ql scene_s56_enet_pc.py               Scene_s56_enet_pc
manim -ql scene_s57_reg_table.py             Scene_s57_reg_table
manim -ql scene_s61_feat_eng.py              Scene_s61_feat_eng
manim -ql scene_s62_interactions.py          Scene_s62_interactions
manim -ql scene_s63_encoding.py              Scene_s63_encoding
manim -ql scene_s66_bias_variance.py         Scene_s66_bias_variance
manim -ql scene_s68_bv_table.py              Scene_s68_bv_table
manim -ql scene_s71_cv_pc.py                 Scene_s71_cv_pc
manim -ql scene_s72_pipeline.py              Scene_s72_pipeline
manim -ql scene_s73_pipeline_pc.py           Scene_s73_pipeline_pc
manim -ql scene_s74_lr_params.py             Scene_s74_lr_params
manim -ql scene_s75_ridge_params.py          Scene_s75_ridge_params
manim -ql scene_s76_lasso_params.py          Scene_s76_lasso_params
manim -ql scene_s77_enet_params.py           Scene_s77_enet_params
manim -ql scene_s78_when_to_use.py           Scene_s78_when_to_use
manim -ql scene_s80_interview_qa.py          Scene_s80_interview_qa
manim -ql scene_s81_summary.py               Scene_s81_summary
echo All 45 fixed scenes done!
pause